export const ADD_SINGLE_RESOURCE = 'ADD_SINGLE_RESOURCE';
export const RECEIVE_GRANT_DATA = 'RECEIVE_GRANT_DATA';
export const SET_ACTIVE_CATEGORIES = 'SET_ACTIVE_CATEGORIES';
export const SET_ACTIVE_LIST = 'SET_ACTIVE_LIST';
export const SET_ACTIVITY_LIST = 'SET_ACTIVITY_LIST';
export const SET_FILTER_STATE = 'SET_FILTER_STATE';
export const SET_LIST_STATE = 'SET_LIST_STATE';
export const SET_LOAD_STATUS = 'SET_LOAD_STATUS';
export const SET_LOCATION_LIST = 'SET_LOCATION_LIST';
export const SET_RESOURCES = 'SET_RESOURCES';
export const TOGGLE_LANGUAGE = 'TOGGLE_LANGUAGE';
export const pushIgphotos = 'pushIgphotos';









